/**
 * VPAT Negligible Impact Post-Processor
 * 
 * This is a SEPARATE service that runs AFTER scorecard generation.
 * It does NOT modify the criterion extraction or evaluation process.
 * 
 * Purpose: Detect criteria with negligible impact and auto-mark as "Supports"
 */

import * as XLSX from 'xlsx'

export interface NegligibleImpactResult {
  processedCount: number
  overriddenCriteria: Array<{
    criterionId: string
    criterionName: string
    originalConformance: string
    impactValue: string
    rowNumber: number
  }>
}

export class VPATNegligiblePostProcessor {
  
  private negligibleKeywords = [
    'negligent',
    'negligible',
    'none',
    'nill',
    'null',
    'no impact',
    'minimal',
    'not applicable',
    'n/a',
    'not relevant',
    'insignificant',
    'trivial',
    'zero impact',
    'does not apply',
    'not important',
    'low priority'
  ]

  /**
   * Process an Excel scorecard buffer and override negligible impact criteria
   * This runs AFTER the scorecard has been generated by the existing service
   */
  async processScorecard(
    scorecardBuffer: Buffer
  ): Promise<{
    modifiedBuffer: Buffer
    result: NegligibleImpactResult
  }> {
    const workbook = XLSX.read(scorecardBuffer, { type: 'buffer' })
    
    const result: NegligibleImpactResult = {
      processedCount: 0,
      overriddenCriteria: []
    }

    // Process each worksheet
    const sheetNames = workbook.SheetNames
    
    for (const sheetName of sheetNames) {
      const worksheet = workbook.Sheets[sheetName]
      const data = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: '' }) as any[][]
      
      if (data.length === 0) continue
      
      // Find column indices from header row
      const headers = data[0] as string[]
      let impactColumnIndex: number | null = null
      let conformanceColumnIndex: number | null = null
      let remarksColumnIndex: number | null = null
      let criterionIdColumnIndex: number | null = null
      let criterionNameColumnIndex: number | null = null
      
      headers.forEach((header, index) => {
        const headerValue = header?.toString().toLowerCase().trim() || ''
        
        // Look for Impact column
        if (headerValue.includes('impact') || 
            headerValue === 'impact' ||
            headerValue.includes('priority') ||
            headerValue.includes('importance')) {
          impactColumnIndex = index
        }
        
        // Look for Conformance/Status column
        if (headerValue.includes('conformance') || 
            headerValue.includes('status') ||
            headerValue.includes('support') ||
            headerValue.includes('result')) {
          conformanceColumnIndex = index
        }
        
        // Look for Remarks column
        if (headerValue.includes('remark') || 
            headerValue.includes('comment') ||
            headerValue.includes('note')) {
          remarksColumnIndex = index
        }
        
        // Look for Criterion ID
        if (headerValue.includes('criterion') && headerValue.includes('id')) {
          criterionIdColumnIndex = index
        }
        
        // Look for Criterion Name
        if (headerValue.includes('criterion') && 
            (headerValue.includes('name') || headerValue.includes('description'))) {
          criterionNameColumnIndex = index
        }
      })
      
      // If we found the necessary columns, process data rows
      if (impactColumnIndex !== null && conformanceColumnIndex !== null) {
        for (let rowIndex = 1; rowIndex < data.length; rowIndex++) {
          const row = data[rowIndex]
          
          // Get impact value - could be in same cell or check adjacent cells
          let impactValue = row[impactColumnIndex]?.toString().toLowerCase().trim() || ''
          
          // Also check the next cell if impact column exists but is empty
          if (!impactValue && impactColumnIndex + 1 < row.length) {
            impactValue = row[impactColumnIndex + 1]?.toString().toLowerCase().trim() || ''
          }
          
          // Check if impact value contains negligible keywords
          const isNegligible = this.negligibleKeywords.some(keyword => 
            impactValue.includes(keyword)
          )
          
          if (isNegligible) {
            const originalConformance = row[conformanceColumnIndex]?.toString() || ''
            
            // Only override if not already "Supports"
            if (!originalConformance.toLowerCase().includes('supports') ||
                originalConformance.toLowerCase().includes('not support') ||
                originalConformance.toLowerCase().includes('does not support')) {
              
              // Override to "Supports"
              row[conformanceColumnIndex] = 'Supports'
              
              // Add explanation to remarks
              if (remarksColumnIndex !== null) {
                const existingRemarks = row[remarksColumnIndex]?.toString() || ''
                const explanation = `Auto-marked as Supports due to negligible impact (${impactValue})`
                
                row[remarksColumnIndex] = existingRemarks 
                  ? `${existingRemarks} | ${explanation}`
                  : explanation
              }
              
              // Track the override
              result.overriddenCriteria.push({
                criterionId: criterionIdColumnIndex !== null
                  ? row[criterionIdColumnIndex]?.toString() || `Row ${rowIndex + 1}`
                  : `Row ${rowIndex + 1}`,
                criterionName: criterionNameColumnIndex !== null
                  ? row[criterionNameColumnIndex]?.toString() || 'Unknown'
                  : 'Unknown',
                originalConformance,
                impactValue,
                rowNumber: rowIndex + 1
              })
              
              result.processedCount++
            }
          }
        }
      }
      
      // Update the worksheet with modified data
      const newWorksheet = XLSX.utils.aoa_to_sheet(data)
      workbook.Sheets[sheetName] = newWorksheet
    }

    // Generate modified buffer
    const modifiedBuffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }) as Buffer

    return {
      modifiedBuffer,
      result
    }
  }

  /**
   * Check if a scorecard has an Impact column
   */
  async hasImpactColumn(scorecardBuffer: Buffer): Promise<boolean> {
    try {
      const workbook = XLSX.read(scorecardBuffer, { type: 'buffer' })
      
      for (const sheetName of workbook.SheetNames) {
        const worksheet = workbook.Sheets[sheetName]
        const data = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: '' }) as any[][]
        
        if (data.length === 0) continue
        
        const headers = data[0] as string[]
        const hasImpact = headers.some(header => {
          const headerValue = header?.toString().toLowerCase().trim() || ''
          return headerValue.includes('impact') || 
                 headerValue.includes('priority') ||
                 headerValue.includes('importance')
        })
        
        if (hasImpact) return true
      }
      
      return false
    } catch (error) {
      console.error('[NEGLIGIBLE POST-PROCESSOR] Error checking for Impact column:', error)
      return false
    }
  }
}

export const vpatNegligiblePostProcessor = new VPATNegligiblePostProcessor()
